microsoft/google-play-vsts-extension

Tasks/google-play-promote/task.json, Tasks/google-play-release/GooglePlay.js, Tasks/google-play-release/task.json, Tasks/google-play-rollout-update/task.json
This PR adds the UI and mechanism for allowing optional multiple apk upload.
@lostintangent @shishirx34
=> Add multiapk upload

vsts-extension-google-play.json
=> Improve help for private key field

Tasks/google-play-release/GooglePlay.ts, Tasks/google-play-release/task.json, Tasks/google-play-release/task.loc.json, package.json, vsts-extension-google-play.json
=> Merge users/arukhlin/v1.117 to master

Tasks/google-play-rollout-update/google-play-rollout-update.ts, Tasks/google-play-rollout-update/task.json, Tasks/google-play-rollout-update/task.loc.json, vsts-extension-google-play.json
This is a bug introduced in last major refactoring and as a result I think the jwtClient is never properly set.
=> Fix jwtClient being null

README.md, Tasks/google-play-release-bundle/task.json, Tasks/google-play-release-bundle/task.loc.json
Some changes needed to prepare the new task for marketplace release
=> Update doc and fix task json

package-lock.json, package.json, vsts-extension-google-play.json
since the upload of 3.160.0 failed in validation, the marketplace is forcing my to create a new version :(
=> update patch version of the extension

Tasks/google-play-release-bundle/GooglePlay.ps1
Any chance this simple correction could fix #142? I'm not super familiar with ADO tasks, but as far as I could tell the ts script worked in my testing.
=> Added missing comma to ps script

Tasks/google-play-promote/task.json, Tasks/google-play-promote/task.loc.json, Tasks/google-play-release-bundle/task.json, Tasks/google-play-release-bundle/task.loc.json, Tasks/google-play-release/task.json, Tasks/google-play-release/task.loc.json, Tasks/google-play-rollout-update/task.loc.json, package.json, vsts-extension-google-play.json
=> Bumped version to 169

Tasks/google-play-promote/google-play-promote.ts, Tasks/google-play-promote/task.json, Tasks/google-play-promote/task.loc.json, Tasks/google-play-release-bundle/task.json, Tasks/google-play-release-bundle/task.loc.json, Tasks/google-play-release/task.json, Tasks/google-play-release/task.loc.json, Tasks/google-play-rollout-update/task.json, Tasks/google-play-rollout-update/task.loc.json, package.json, vsts-extension-google-play.json
=> Bumbed version to 170

Tasks/google-play-promote/task.json, Tasks/google-play-promote/task.loc.json, Tasks/google-play-release-bundle/task.json, Tasks/google-play-release-bundle/task.loc.json, Tasks/google-play-release/task.json, Tasks/google-play-release/task.loc.json, Tasks/google-play-rollout-update/task.json, Tasks/google-play-rollout-update/task.loc.json, package.json, vsts-extension-google-play.json
Bumped tasks version to 172  to prepare for the new release
=> Bumped version to 172

.github/pull_request_template.md, docs/taskversionbumping.md
Copied changes of https://github.com/microsoft/azure-pipelines-tasks/pull/13081
=> Added PR template. Added instructions for task version bumping

baseREADME.md
**Task name**: Google play release bundle - docs
**Description**: Updated readme - moved contact us sections to the bottom.
**Documentation changes required:** n/a
**Added unit tests:** n/a
**Attached related issue:** n/a
**Checklist**:
=> Moved contact section to the bottom

README.md, baseREADME.md, docs/vsts-README.md
**Task name**: Google play release bundle
**Description**:  amended readme files (readme file for repo and extension.
**Documentation changes required:** n/a
**Added unit tests:** n/a
**Attached related issue:** -
**Checklist**:
=> Amended readme - repo and vsts extension

README.md
**Task name**: Google play release bundle
**Description**: Amended readme - moved contact us to the bottom
**Documentation changes required:**  n/a
**Added unit tests:** (Y/N) n/a
**Attached related issue:** (Y/N) -
**Checklist**:
=> Moved contact us to the bottom of readme

README.md, docs/vsts-README.md
Updated readme file due to changes in the azure devops UI
=> Update Readme file

Tasks/GooglePlayPromote/package-lock.json, Tasks/GooglePlayPromote/task.json, Tasks/GooglePlayPromote/task.loc.json, Tasks/GooglePlayRelease/package-lock.json, Tasks/GooglePlayRelease/task.json, Tasks/GooglePlayRelease/task.loc.json, Tasks/GooglePlayReleaseBundle/package-lock.json, Tasks/GooglePlayReleaseBundle/task.json, Tasks/GooglePlayReleaseBundle/task.loc.json, Tasks/GooglePlayRolloutUpdate/package-lock.json, Tasks/GooglePlayRolloutUpdate/task.json, Tasks/GooglePlayRolloutUpdate/task.loc.json, package-lock.json
**Task name**: All extension tasks
**Description**: Deduplicated packages
**Checklist**:
=> Deduplicated packages.

package-lock.json, package.json, vsts-extension-google-play.json
**Description**: Update package version from 183 to 185 to prepare for release
=> Update package version from 183 to 185 to prepare for release

Tasks/GooglePlayPromote/task.json, Tasks/GooglePlayPromote/task.loc.json, Tasks/GooglePlayRelease/task.json, Tasks/GooglePlayRelease/task.loc.json, Tasks/GooglePlayReleaseBundle/task.json, Tasks/GooglePlayReleaseBundle/task.loc.json, Tasks/GooglePlayRolloutUpdate/task.json, Tasks/GooglePlayRolloutUpdate/task.loc.json
**Task name**: All tasks.
**Description**: applied command restrictions.
**Checklist**:
=> Applied restrictions for google play tasks

Tasks/GooglePlayRolloutUpdate/package-lock.json, Tasks/GooglePlayRolloutUpdate/package.json, Tasks/GooglePlayRolloutUpdate/task.json, Tasks/GooglePlayRolloutUpdate/task.loc.json
**Task name**: GooglePlayRolloutUpdate
* Updated _googleapis_ to 67.1.0 to resolve vulnerabilities in depended packages.
* Updated _google-auth-library_ to 7.0.2 to resolve vulnerabilities in depended packages.
* Updated _azure-pipelines-task-lib_ to 3.1.0 to use not preview version
**Checklist**:
[Reference ](https://abtttestorg.visualstudio.com/AndroidSigningTest/_build/results?buildId=2965&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9) to test pipeline
=> [GooglePlayRolloutUpdate] Updated dependencies

Tasks/GooglePlayReleaseBundle/package-lock.json, Tasks/GooglePlayReleaseBundle/package.json, Tasks/GooglePlayReleaseBundle/task.json, Tasks/GooglePlayReleaseBundle/task.loc.json
**Task name**: GooglePlayReleaseBundle
* Updated _googleapis_ to 67.1.0 to resolve vulnerabilities in depended packages.
* Updated _google-auth-library_ to 7.0.2 to resolve vulnerabilities in depended packages.
* Updated _azure-pipelines-task-lib_ to 3.1.0 to use not preview version
**Checklist**:
[Reference ](https://abtttestorg.visualstudio.com/AndroidSigningTest/_build/results?buildId=2964&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9) to test pipeline
=> [GooglePlayReleaseBundle] Updated dependencies

Tasks/GooglePlayPromote/task.json, Tasks/GooglePlayPromote/task.loc.json, Tasks/GooglePlayRolloutUpdate/task.json, Tasks/GooglePlayRolloutUpdate/task.loc.json, package-lock.json, package.json, vsts-extension-google-play.json
Description: Update package version from 185 to 187 to prepare for release
=> Bump up extension version

package-lock.json, package.json, vsts-extension-google-play.json
Description: update version to 188 to prepare for release
=> bump up the version for the 189th release

package-lock.json, package.json, vsts-extension-google-play.json
=> Bump version to 192

package-lock.json, package.json, vsts-extension-google-play.json
**Task name**: All tasks
**Description**: Bumped up extension version from 4.201.0 to 4.203.0
**Added unit tests:** (Y/N) No
=> Bump Google Play Extension version to 4.203.0

Localize/LocProject.json
This PR adds LocProject template from Localization flow
=> [Localization] Update LocProject

Localize/localize-pipeline.yml, ci/localization-updates/send-notifications.ps1, ci/open-pullrequest.ps1
This PR updates YAML template and related scripts for Localization flow.
=> [Localization] Update YAML template for Localization flow

Localize/loc/de-DE/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/es-ES/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/fr-FR/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/it-IT/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ja-JP/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ko-KR/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ru-RU/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-CN/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-TW/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230307104627952 to Localization with localized lcls
=> LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230307104627952 to Localization

Localize/loc/it-IT/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/it-IT/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/it-IT/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/it-IT/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ja-JP/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ja-JP/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ja-JP/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ja-JP/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ko-KR/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ko-KR/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ko-KR/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ko-KR/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-CN/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-CN/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-CN/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-CN/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230307223552248 to Localization with localized lcls
=> LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230307223552248 to Localization

Localize/loc/fr-FR/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/fr-FR/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/fr-FR/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/fr-FR/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230308101401818 to Localization with localized lcls
=> LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230308101401818 to Localization

Localize/loc/de-DE/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/de-DE/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/de-DE/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/de-DE/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/es-ES/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/es-ES/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/es-ES/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/es-ES/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ru-RU/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ru-RU/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ru-RU/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ru-RU/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-TW/Tasks/GooglePlayIncreaseRolloutV2/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-TW/Tasks/GooglePlayPromoteV3/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-TW/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-TW/Tasks/GooglePlayStatusUpdateV2/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230308221923753 to Localization with localized lcls
=> LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230308221923753 to Localization

Localize/loc/de-DE/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/es-ES/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/fr-FR/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/it-IT/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ko-KR/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ru-RU/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-CN/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-TW/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230309222737909 to Localization with localized lcls
=> LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20230309222737909 to Localization

Tasks/GooglePlayReleaseV4/modules/googleutil.ts, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, vsts-extension-google-play.json
***Task name:*** GooglePlayReleaseV4
***Description:*** Add retries for a known Google API error.
***Documentation changes required:*** No
***Added unit tests:*** No
Related issues: #388 #417
***Checklist:***
=> Add retries for a known Google API error

Tasks/GooglePlayReleaseV4/modules/googleutil.ts
***Task name:*** GooglePlayReleaseV4
***Description:*** Add a message for a known Google API error.
***Documentation changes required:*** No
***Added unit tests:*** No
[Related issue](https://github.com/microsoft/google-play-vsts-extension/issues/417)
***Checklist:***
=> Add message for a known Google API error

make.js
**Description**: Tests were failing because one of async functions was not awaited
**Checklist**:
=> Fix tests execution error in make.json

Localize/loc/fr-FR/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/it-IT/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ru-RU/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-CN/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/zh-TW/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20240212221712911 to Localization with localized lcls
=> LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20240212221712911 to Localization

Localize/loc/de-DE/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/es-ES/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ja-JP/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl, Localize/loc/ko-KR/Tasks/GooglePlayReleaseV4/Strings/resources.resjson/en-US/resources.resjson.lcl
LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20240214020821698 to Localization with localized lcls
=> LEGO: Pull request from lego/hb_231749d5-1bb8-45dd-83b0-f40375af4ab4_20240214020821698 to Localization

Tasks/GooglePlayReleaseV4/main.ts, Tasks/GooglePlayReleaseV4/modules/fileHelper.ts, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, vsts-extension-google-play.json
**Task name**: Upload mapping file for AAB files
**Description**: Ideally AAB file already contain mapping file in them but there is an issue from Google side due to which mapping files are getting removed from AAB files. So, we need to upload them similar to APK files.
**Checklist**:
=> Mapping file for bundles

azure-pipelines.yml
**Task name**: -
fix artifact directory
**Documentation changes required:**N
**Checklist**:
=> fix artifact directory

.npmrc, Tasks/GooglePlayIncreaseRolloutV2/.npmrc, Tasks/GooglePlayIncreaseRolloutV2/package-lock.json, Tasks/GooglePlayPromoteV3/.npmrc, Tasks/GooglePlayPromoteV3/package-lock.json, Tasks/GooglePlayReleaseV4/.npmrc, Tasks/GooglePlayReleaseV4/package-lock.json, Tasks/GooglePlayStatusUpdateV2/.npmrc, Tasks/GooglePlayStatusUpdateV2/package-lock.json, azure-pipelines.yml, dev-dependencies-constants.js, make.js, package-lock.json
**Description**: This PR adds **.npmrc** to all packages in the repository to consume packages from the internal feed.
**Related**: [AB#2197030](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2197030)
=> Migration to CFS
