Tasks/google-play-promote/task.json
This PR simply updates the source and destination track fields to reflect reality, since you can't promote an APK to the `alpha` track or from the `production` track.
=> Update promote task

Tasks/google-play-release/GooglePlay.js
VSTS tries to be smart when passing back paths with spaces in them by wrapping them in quotes.
Unfortunately, the backend package we use to parse the apks was already smart about this, so the extra quotes were being considered as part of the path instead of as wrappers around the path.
This caused the path resolution to break, which caused apk parsing to fail.
Fix is to remove these extra quotes when we resolve the glob paths.
@lostintangent @shishirx34 @geof90
=> Fix spaces in path

Tasks/google-play-release/GooglePlay.js, Tasks/google-play-release/task.json
Add the ability to specify where the metadata folder is.
Needed this because the default locations for Release and Build were different.
Added task failure if a metadata step fails.
@lostintangent @shishirx34
=> adding metadata folder specification

Tasks/google-play-release/GooglePlay.js, Tasks/google-play-release/task.json, vsts-extension-google-play.json
Properly assigning APK to track using its version code
Properly set version code when updating recent changes, based on change log file name
=> Multiple apk fix assign to track

Tasks/google-play-release/GooglePlay.js, Tasks/google-play-release/task.json, vsts-extension-google-play.json
Fixing image upload [issue](https://github.com/Microsoft/google-play-vsts-extension/issues/29), getImageList not returning full path to image file.
=> Fixing image path for screenshots folders

package.json
Cloning, running npm install and then 'gulp' would fail if typings@2.0.0 is not installed.  Make it a local dependency so it 'just works'.  (This check is found at https://github.com/Microsoft/google-play-vsts-extension/blob/master/make.js#L107)
=> Add typings@2.0.0 as dependency

README.md, Tasks/google-play-promote/google-play-promote.ts, Tasks/google-play-promote/task.json, Tasks/google-play-promote/task.loc.json, Tasks/google-play-release/GooglePlay.ts, Tasks/google-play-release/task.json, Tasks/google-play-release/task.loc.json, baseREADME.md, docs/vsts-README.md
Fix https://github.com/Microsoft/google-play-vsts-extension/issues/90 by adding support for new internal test track. Made the following changes:
Publish task: Added internal test as target and set internal as default
Promote task: Added internal test as source and default, added alpha as target
As internal test will probably be used for most automated deployments, I configured it as default.
=> Add support for internal test track

Tasks/google-play-promote/task.json, Tasks/google-play-promote/task.loc.json, Tasks/google-play-release-bundle/GooglePlay.ps1, Tasks/google-play-release-bundle/GooglePlay.ts, Tasks/google-play-release-bundle/Tests/L0.ts, Tasks/google-play-release-bundle/Tests/L0AttachMetadata.ts, Tasks/google-play-release-bundle/Tests/L0BadVersionList.ts, Tasks/google-play-release-bundle/Tests/L0DeobfuscationFileNotFound.ts, Tasks/google-play-release-bundle/Tests/L0FoundDeobfuscationFile.ts, Tasks/google-play-release-bundle/Tests/L0HappyPath.ts, Tasks/google-play-release-bundle/Tests/L0NoBundleFound.ts, Tasks/google-play-release-bundle/Tests/L0NoBundleSupplied.ts, Tasks/google-play-release-bundle/Tests/L0NoPackageNameSupplied.ts, Tasks/google-play-release-bundle/Tests/L0UpdateTrackWithVersionList.ts, Tasks/google-play-release-bundle/Tests/L0UseChangeLog.ts, Tasks/google-play-release-bundle/Tests/L0UseChangeLogFail.ts, Tasks/google-play-release-bundle/task.json, Tasks/google-play-release-bundle/task.loc.json, Tasks/google-play-release/task.json, Tasks/google-play-release/task.loc.json, Tasks/google-play-rollout-update/task.json, Tasks/google-play-rollout-update/task.loc.json, package-lock.json, package.json, vsts-extension-google-play.json
The newer bundle task took a dependency on a new version of the google api that internally uses asyc/await. But the default execution for tasks happens in node 6 which doesn't support async await. This was causing #142 
I've changed this task to execute using node 10 which supports async/await
Additionally, there was an input name mismatch where the task json declared the input applicationId but internally assumed it was named packageName. Looking through the code I suspect these were intended to be the same thing so I've changed the code to look up applicationId.
Bump version number everywhere to 164
=> Bundle Task: fix input name and use node 10

Tasks/google-play-promote/task.json, Tasks/google-play-promote/task.loc.json, Tasks/google-play-release-bundle/task.json, Tasks/google-play-release-bundle/task.loc.json, Tasks/google-play-release/GooglePlay.ts, Tasks/google-play-release/task.json, Tasks/google-play-release/task.loc.json, Tasks/google-play-rollout-update/task.json, Tasks/google-play-rollout-update/task.loc.json, package-lock.json, package.json, vsts-extension-google-play.json
This sets the track input for all tasks to be editable. Meaning you can type in your own track if you don't want to use one of the predefined alpha, beta, etc tracks.
=> allow track to be editable. Extra logging on exception

Tasks/google-play-promote/package.json, Tasks/google-play-promote/task.json, Tasks/google-play-release/package.json, Tasks/google-play-release/task.json
Related issus: https://github.com/microsoft/google-play-vsts-extension/issues/178, https://github.com/microsoft/google-play-vsts-extension/issues/130
This PR fixes "error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol" issue. This error occurred when using the old version of googleapi. Therefore, the version was updated in this PR. Googleapis dependency for googgle-play-promote has also been updated to avoid the same error for this task. So now all tasks in google-play-extension have googleapis dependency v34+
google-play-release run with updated googleapis:
=> [google-play-release] Update googleapis dependency to v34.0.0 

Tasks/google-play-promote/google-play-promote.ts, Tasks/google-play-promote/googleutil.ts, Tasks/google-play-promote/task.json, Tasks/google-play-promote/task.loc.json
**Task name**: google-play-promote
**Description**: This PR adds the ability to disable source track cleanup. An additional checkbox "Clean the source track" has been added, the checkbox is checked by default. If you want to keep the source track after the "promote" operation, please uncheck this box. Also in this PR added logging for the status of the track after the "Promote" operation.
**Documentation changes required:** (Y) 
**Added unit tests:** (N) 
**Attached related issue:** (Y) https://github.com/microsoft/google-play-vsts-extension/issues/166
**Checklist**:
=> [google-play-promote] Ability to disable track cleanup

Tasks/google-play-promote/Strings/resources.resjson/en-US/resources.resjson, Tasks/google-play-promote/task.json, Tasks/google-play-promote/task.loc.json, Tasks/google-play-release-bundle/task.json, Tasks/google-play-release-bundle/task.loc.json, Tasks/google-play-rollout-update/task.json, Tasks/google-play-rollout-update/task.loc.json, package.json, vsts-extension-google-play.json
**Task name**: 
- GooglePlayPromote
- GooglePlayReleaseBundle
- GooglePlayIncreaseRollout
Bumped tasks version to 174 to prepare for the new release
*Changes:*
- Bumped tasks  version to 174 
- Bumped extension version to 174
**Added unit tests:** N 
**Attached related issue:** 
- https://github.com/microsoft/build-task-team/issues/194
**Checklist**:
**Note**:
- I added `resources.resjson` changes  for `Google Promote Task`  since were lost in related [PR](https://github.com/microsoft/google-play-vsts-extension/pull/190)
=> [GooglePlayExtension] Bump extension version to 174

make-util.js
The fix was [introduced here.](https://github.com/microsoft/app-store-vsts-extension/pull/209)
[GooglePlayExtension CI pipeline](https://dev.azure.com/mseng/AzureDevOps/_build/results?buildId=14261737&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=b6d2c347-7b49-5fd1-6216-64895449178b) is failing on `gulp create` while migrating tasks to node10 (on macOS and Ubuntu)
```
Creating PRODUCTION vsix...
[13:49:05] '<anonymous>' errored after 3.28 s
[13:49:05] Error: exited with error code: 255
at ChildProcess.onexit (/Users/runner/work/1/s/node_modules/end-of-stream/index.js:40:36)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[13:49:05] 'packageprod' errored after 4.61 s
```
It looks like the …
=> [build script] Remove tsc and tsserver symbolic links

Tasks/GooglePlayRelease/task.json, Tasks/GooglePlayRelease/task.loc.json
**Task name**: GooglePlayReleaseV3
**Description**:
This PR fixes the visibility issue of the `Deobfuscation path` filed when the `Update Metadata` check-box is unchecked.
**Attached related issue:** #231
**UI screenshot**: 
_Before_:
_After_:
**Checklist**:
=> [GooglePlayReleaseV3] Fix visibility of "Deobfuscation path" input 

package-lock.json, package.json, vsts-extension-google-play.json
Bump extension version to 183 for the extension release
*Changes:*
- Bumped extension version to 183
**Added unit tests:** N 
**Attached related issue:** 
- https://github.com/microsoft/build-task-team/issues/852
**Checklist**:
=> [GooglePlayExtension] Bump extension version to 183

Tasks/GooglePlayRelease/package-lock.json, Tasks/GooglePlayRelease/package.json, Tasks/GooglePlayRelease/task.json, Tasks/GooglePlayRelease/task.loc.json
**Task name**: GooglePlayRelease
* Updated _googleapis_ to 67.1.0 to resolve vulnerabilities in depended packages.
* Updated _google-auth-library_ to 7.0.2 to resolve vulnerabilities in depended packages.
* Updated _azure-pipelines-task-lib_ to 3.1.0 to use not preview version
**Checklist**:
[Reference ](https://abtttestorg.visualstudio.com/AndroidSigningTest/_build/results?buildId=2966&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9) to test pipeline
=> [GooglePlayRelease] Update dependencies

Tasks/GooglePlayPromote/package-lock.json, Tasks/GooglePlayPromote/package.json, Tasks/GooglePlayPromote/task.json, Tasks/GooglePlayPromote/task.loc.json
**Task name**: GooglePlayPromote
* Updated _googleapis_ to 67.1.0 to resolve vulnerabilities in depended packages.
* Updated _google-auth-library_ to 7.0.2 to resolve vulnerabilities in depended packages.
* Updated _azure-pipelines-task-lib_ to 3.1.0 to use not preview version
**Checklist**:
[Reference ](https://abtttestorg.visualstudio.com/AndroidSigningTest/_build/results?buildId=2966&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9) to test pipeline
=> [GooglePlayPromote] Update dependencies

Tasks/GooglePlayPromote/Strings/resources.resjson/en-US/resources.resjson, Tasks/GooglePlayPromote/google-play-promote.ts, Tasks/GooglePlayPromote/task.json, Tasks/GooglePlayPromote/task.loc.json
**Task name**: GooglePlayPromote
**Checklist**:
=> [GooglePlayPromote] Fix task not failing when versionCode is not valid

gulpfile.js
**Description**: We've noticed that .d.ts files compose the majority of node_modules' folder size. Removing these files decreases extension size from ~36mb to ~12 mb.
**Checklist**:
=> Remove all .d.ts files on .vsix creation to decrease extension bundle size

Tasks/GooglePlayReleaseBundle/GooglePlay.ts, Tasks/GooglePlayReleaseBundle/Strings/resources.resjson/en-US/resources.resjson, Tasks/GooglePlayReleaseBundle/task.json, Tasks/GooglePlayReleaseBundle/task.loc.json
**Task name**: Google Play release bundle
Added new input changesNotSentForReview. If the customer selects this option, changes will be sent to review.
I used the **@ts-ignore** comment because we don't have **changesNotSentForReview** option in edtits.commit method yet.
The changes for that option were added to the repo but the package with them has not released. [info](https://github.com/googleapis/google-api-nodejs-client/commit/a2ca59d046ebb7381c68298ad81edb80a84d6bcf#diff-d6bb74fc5fb7d9b91b45bc68d11d38099ee2fff3dcb853d27e2713ca2d5aa7bfR1967). 
With **@ts-ignore** all goes well.
I think we couldn't reproduce this issue because we didn't have any rejections in Google Play Console and all our changes were send automatically. The customer had ones and it probably …
=> [GooglePlayReleaseBundle]Add changesNotSentForReview option

.github/workflows/autoAssignABTT.yml
**Task name**: N/A (changes for github action only)
**Description**: updated auto assign ABTT action - to add area and triage label to opened issues, and assign them to team board.
**Documentation changes required:**  N
**Checklist**:
=> Updated autoassign action

Tasks/GooglePlayReleaseBundle/GooglePlay.ts, Tasks/GooglePlayReleaseBundle/Strings/resources.resjson/en-US/resources.resjson, Tasks/GooglePlayReleaseBundle/Tests/L0.ts, Tasks/GooglePlayReleaseBundle/Tests/L0GoogleUtil.ts, Tasks/GooglePlayReleaseBundle/googleutil.ts, Tasks/GooglePlayReleaseBundle/task.json, Tasks/GooglePlayReleaseBundle/task.loc.json
**Task name**: GooglePlayReleaseBundle
**Description**: Add input "Release Name" for Bundle Release task. 
**Documentation changes required:** (Y/N) Y
**Attached related issue:** (Y/N) #257 
**Checklist**:
=> [GooglePlayReleaseBundle] Add input parameter to define Release-Name

Tasks/GooglePlayStatusUpdate/task.json, Tasks/GooglePlayStatusUpdate/task.loc.json, package-lock.json, package.json, vsts-extension-google-play.json
Looks like the there is already a task on the marketplace with the same guild as GooglePlayStatusUpdate; generated a new guid and bumped extension version
=> Fix taken GooglePlayStatusUpdate task guid; bump extension version

Tasks/GooglePlayRelease/GooglePlay.ts, Tasks/GooglePlayRelease/Strings/resources.resjson/en-US/resources.resjson, Tasks/GooglePlayRelease/task.json, Tasks/GooglePlayRelease/task.loc.json, Tasks/GooglePlayReleaseBundle/GooglePlay.ts, Tasks/GooglePlayReleaseBundle/Strings/resources.resjson/en-US/resources.resjson, Tasks/GooglePlayReleaseBundle/task.json, Tasks/GooglePlayReleaseBundle/task.loc.json, vsts-extension-google-play.json
**Task name**: GooglePlayReleaseV3, GooglePlayReleaseBundleV3
**Description**: Added deprecation warnings since we're planning to remove these tasks
**Documentation changes required:** Yes - prepare a migration guide
**Checklist**:
=> [GooglePlayReleaseV3, GooglePlayReleaseBundleV3] Add deprecation warnings

docs/google-play-release-migration.md
**Task name**: GooglePlayRelease
**Description**: The migration documentation for the GooglePlayRelease task mentions the wrong parameter in the 'Releasing a single bundle file' section; 'bundleFile' should be mentioned instead of 'apkFile'
**Documentation changes required:** N (Documentation change only)
**Added unit tests:** N (Documentation change only)
**Attached related issue:** #308
**Checklist**: (N/A)
=> Update documentation for releasing a bundle file

Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, package.json
**Task name**: GooglePlayReleaseV4
**Description**: Move input fields, that have dependency on "action" input, out of "advanced" group to fix error: 
`Task definition input 'action' and Task definition input 'changeUpdatePriority' must belong to same group as they are dependent inputs for Task with ID '8cf7cac0-620b-11e5-b4cf-8565e60f4d27' `
**Attached related issue:** (Y/N) https://github.com/microsoft/google-play-vsts-extension/issues/311
**Checklist**:
I have tested this fix on Azure DevOps Server 2020 and Azure DevOps Server 2019.
I have tried to install Google Play extension 4.195.1 (without fix) to my local instance and got the same error, then I applied my fix, generated my private package with extension and …
=> Fix error while updating from version 3.194.0 to 4.195.1 on Azure DevOps Server

package-lock.json, vsts-extension-google-play.json
**Task name**: All tasks
**Description**: Bumped up extension version from 4.195.1 to 4.196.0
**Added unit tests:** (Y/N) No
**Checklist**:
=> Bump extension version to 4.196.0

README.md, Tasks/GooglePlayReleaseV4/modules/metadataHelper.ts, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, baseREADME.md, docs/vsts-README.md
**Task name**: GooglePlayReleaseV4
**Description**: The changes adds default.txt changelog file to list of required changelog files for uploading.
**Attached related issue:** (Y/N) Y
**Checklist**:
Checked test cases:
1. there is no files in changelogs directory - no one changelog is uploaded with metadata
2. there is file with name different from version number only - no one changelog is uploaded with metadata
3. there is file default.txt only - file default.txt is used as changelog
4. there is file with name equal to version number only - file with name equal to version number is used as changelog
5. there are 2 files: default.txt and file with name equal to version number - file with name equal to version number …
=> Add support default.txt changelog name

package-lock.json, package.json
**Task name**: vso-android-extension
**Description**: This PR should address several security alerts. The list of updated dependencies:
- `tfx-cli` - `^0.11.0` -> `^0.12.0`
- `validator` - `3.33.0` -> `^13.7.0`
- `yargs` - `^6.4.0` -> `^17.5.1`
**Changelog:**
- Applied `npm audit fix` command to update `validator` and `yargs` dependencies;
- `tfx-cli` version is bumped to `^0.12.0`
**Attached related issue:** https://github.com/microsoft/build-task-team/issues/2715
**Checklist**:
=> [vso-android-extension] Fix security warnings

CONTRIBUTING.md, Tasks/GooglePlayPromoteV2/task.json, Tasks/GooglePlayPromoteV2/task.loc.json, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, Tasks/GooglePlayRolloutUpdateV3/task.json, Tasks/GooglePlayRolloutUpdateV3/task.loc.json, Tasks/GooglePlayStatusUpdateV2/task.json, Tasks/GooglePlayStatusUpdateV2/task.loc.json, dev-dependencies-constants.js, make-util.js, make.js, package-lock.json, package.json, vsts-extension-google-play.json
**Description**: Update dependencies and update versions
**Changelog**:
- Updated task versions
- Decreased `mocha` version from 9.2.2 to 6.2.3 (since node 10 support was dropped in mocha 9)
- Fixed "lockfileVersion"
- Updated extension version to 4.207.0
- Added `dev-dependencies constants.js`
- Updated contributing.md (Fixed minimum supported node version to 10.0.0)
**Checklist**:
=> Add dev-dependencies-constants and update mocha version

vsts-extension-google-play.json
Bump `Google Play VSTS extension` version to `4.209.0` for the release 
**Checklist**:
=> bump extension version

.gitignore, Tasks/GooglePlayIncreaseRolloutV2/task.json, vsts-extension-google-play.json
**Task name:** GooglePlayIncreaseRolloutV2
**Description:** we need to update the task id to fix this error:
```
Contribution Microsoft.VisualStudio.Services.TaskId.GOOGLE-PLAY-INCREASE-ROLLOUT
is re-using the task ID of another contribution from an earlier version.
To publish the extension, change the task ID.
```
**ChangeLog:** task id updated; task version updated; extension version updated
**Documentation changes required:** Yes ([docs](https://mseng.visualstudio.com/AzureDevOps/_wiki/wikis/AzureDevOps.wiki/17234/Release-Google-Play-extension) should be updated according to changes in this PR)
[Related issue](https://github.com/microsoft/build-task-team/issues/3394)
**Checklist:**
=> [GooglePlayIncreaseRolloutV2] fix task id

Tasks/GooglePlayReleaseV4/modules/googleutil.ts, Tasks/GooglePlayReleaseV4/package.json, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, vsts-extension-google-play.json
**Task name:** GooglePlayReleaseV4
**Description:** migration to Node 16.
This PR should fix the issue that appears when Node uses OpenSSL to authorize in Google Play.
**Checklist:**
=> GooglePlayReleaseV4 Node 16 migration

Tasks/GooglePlayIncreaseRolloutV2/google-play-increase-rollout.ts, Tasks/GooglePlayIncreaseRolloutV2/googleutil.ts, Tasks/GooglePlayIncreaseRolloutV2/task.json, Tasks/GooglePlayIncreaseRolloutV2/task.loc.json, Tasks/GooglePlayPromoteV3/google-play-promote.ts, Tasks/GooglePlayPromoteV3/googleutil.ts, Tasks/GooglePlayPromoteV3/task.json, Tasks/GooglePlayPromoteV3/task.loc.json, Tasks/GooglePlayReleaseV4/main.ts, Tasks/GooglePlayReleaseV4/modules/googleutil.ts, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, Tasks/GooglePlayStatusUpdateV2/google-play-status-update.ts, Tasks/GooglePlayStatusUpdateV2/googleutil.ts, Tasks/GooglePlayStatusUpdateV2/task.json, Tasks/GooglePlayStatusUpdateV2/task.loc.json, vsts-extension-google-play.json
**Tasks:**
* GooglePlayIncreaseRolloutV2
* GooglePlayPromoteV3
* GooglePlayReleaseV4
* GooglePlayStatusUpdateV2
**ChangeLog:** `googleutil.ts` — added the `authorize` function
**Description:** Remove secret from debug logs
**Attached related issue:** No
**Checklist:**
=> Remove secret from debug logs

Tasks/GooglePlayReleaseV4/main.ts, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, vsts-extension-google-play.json
***Task name:*** GooglePlayReleaseV4
***Description:*** The `versionCodes` property is not defined when version codes do not exist for the latest completed release.
Appropriate fix implemented. Please hide whitespace to review.
***Documentation changes required:*** No
***Added unit tests:*** No
***Attached related issue:*** N/A
***Checklist:***
=> The `versionCodes` property can be `undefined`

Tasks/GooglePlayReleaseV4/main.ts, Tasks/GooglePlayReleaseV4/modules/fileHelper.ts, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, vsts-extension-google-play.json
**Task name**: Support to upload symbols.zip for aab files.
**Description**: We had made changes to upload symbols.zip in this PR https://github.com/microsoft/google-play-vsts-extension/pull/419 but changes for aab files were missed. Making those changes as part of current PR.
**Checklist**:
=> Changes to upload symbols.zip for aab files

Tasks/GooglePlayIncreaseRolloutV2/task.json, Tasks/GooglePlayIncreaseRolloutV2/task.loc.json, Tasks/GooglePlayPromoteV3/task.json, Tasks/GooglePlayPromoteV3/task.loc.json, Tasks/GooglePlayReleaseV4/task.json, Tasks/GooglePlayReleaseV4/task.loc.json, Tasks/GooglePlayStatusUpdateV2/task.json, Tasks/GooglePlayStatusUpdateV2/task.loc.json, vsts-extension-google-play.json
**Description**: Remove build config mapping & bump versions
**Attached related issue:** (Y/N) ICM 508252642
**Checklist**:
=> Remove build config mapping & bump versions

azure-pipelines.yml
**Task name**: Not related to any specific task
**Description**: Added 1ES template pipeline
**Documentation changes required:** Y
**Attached related issue:** [AB#2188514](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2188514)
**Checklist**:
=> Add 1ES template pipeline

package-lock.json
**Task name**: -
bumped regexp package version. 
As the package used only to build the extension, no need to bump the extension version itself.
**Attached related issue:** [AB#2212977](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2212977)
**Checklist**:
=> path-to-regexp CVE fix
